export const LOADBIRTHDAYWEEKDATA = 'LOADBIRTHDAYWEEKDATA';//查詢週生日人员
export const LOADBIRTHDAYMINEDATA = 'LOADBIRTHDAYMINEDATA';//查詢我的祝福
export const PERSONALBIRTHDATDATAUPDATE = 'PERSONALBIRTHDATDATAUPDATE'; // PERSONALBIRTHDATDATAUPDATE
export const REFRESH_WEEK_SUCCESS        = 'REFRESH_WEEK_SUCCESS';   //更新成功
export const REFRESH_MSG_SUCCESS        = 'REFRESH_MSG_SUCCESS';   //更新成功