export const SET_COMPANYDOCUMENT_APPOID = "SET_COMPANYDOCUMENT_APPOID" //加载公司文件AppOid
export const LOAD_COMPANYDOCUMENT_NEWESTDATA = "LOAD_COMPANYDOCUMENT_NEWESTDATA" //加载公司文件最新资料
export const LOAD_COMPANYDOCUMENT_DATA = "LOAD_COMPANYDOCUMENT_DATA"; //加载公司文件资料
export const LOAD_COMPANYDOCUMENT_TYPE = "LOAD_COMPANYDOCUMENT_TYPE"; //加载公司文件分类
export const LOAD_COMPANYDOCUMENT_VISITDATA = "LOAD_COMPANYDOCUMENT_VISITDATA"; //加载公司文件访问数资料
export const ADD_COMPANYDOCUMENT_VISITCOUNT = "ADD_COMPANYDOCUMENT_VISITCOUNT"; //设置公司文件访问数
export const SET_COMPANYDOCUMENT_FILEURLDATA = "SET_COMPANYDOCUMENT_FILEURLDATA"; //设置公司文件fileUrl
export const SET_LOADING = "SET_LOADING"; //设置是否正在加载