export const CREATEFORM_REFRESHING   = 'CREATEFORM_REFRESHING';
export const RENDERFORMFORMAT        = 'RENDERFORMFORMAT'; 
export const RENDERFORMFORMATERROR   = 'RENDERFORMFORMATERROR'; 
export const UPDATEDEFAULTVALUE      = 'UPDATEDEFAULTVALUE';
export const UPDATEDEFAULTVALUEERROR = 'UPDATEDEFAULTVALUEERROR';
export const CLOSECREATEFORM         = 'CLOSECREATEFORM';
export const CHECKREQUIREDVALUE      = 'CHECKREQUIREDVALUE';
export const REGISTERFORMRESULT      = 'REGISTERFORMRESULT';
export const DEFAULTSUBMITRESULT     = 'DEFAULTSUBMITRESULT';

