export const DAILYORALENGLISH_LOADDATA = 'DAILYORALENGLISH_LOADDATA'; //加载资料
export const DAILYORALENGLISH_LOADMOREDATA = 'DAILYORALENGLISH_LOADMOREDATA'; //加载更多资料
export const SET_DAILYORALENGLISH_TOTALCOUNT = 'SET_DAILYORALENGLISH_TOTALCOUNT'; //设置资料总笔数
export const SET_DAILYORALENGLISH_PAGESIZE = 'SET_DAILYORALENGLISH_PAGESIZE'; //设置一页笔数
export const SET_DAILYORALENGLISH_PAGENUM = 'SET_DAILYORALENGLISH_PAGENUM'; //设置页数
export const SET_DAILYORALENGLISH_LOADING = 'SET_DAILYORALENGLISH_LOADING'; //设置加载状态