export const FORM_REFRESHING                      = 'FORM_REFRESHING';   		//更新中→此部分更新指畫面更新
export const FORM_REFRESH_ERROR                   = 'FORM_REFRESH_ERROR';  		//更新出錯
export const FORM_REFRESH_SUCCESS                 = 'FORM_REFRESH_SUCCESS';  	//更新成功
export const LOADFORMTYPES                        = 'LOADFORMTYPES'; 		
export const LOADFORMSIGNS                        = 'LOADFORMSIGNS';	
export const LOADFORMCONTENT                      = 'LOADFORMCONTENT';
export const LOADFORMTYPESERROR                   = 'LOADFORMTYPESERROR';
export const SUBMITRESULT                         = 'SUBMITRESULT';
export const INITIALSTATE                         = 'INITIALSTATE';
export const FORMSIGNDONE                         = 'FORMSIGNDONE';				//確定表單簽核流程結束
export const SET_COMPANIES_FORMSIGN               = 'SET_COMPANIES_FORMSIGN'; 	//設定表單簽核的開單公司清單
export const DELETEALLFORMS                       = 'DELETEALLFORMS'; 			//登出時消除所有簽核表單
export const UPDATEDEFAULTVALUE_FOR_FORMSIGN      = 'UPDATEDEFAULTVALUE_FOR_FORMSIGN'; 		// 編輯表單資料
export const UPDATEDEFAULTVALUEERROR_FOR_FORMSIGN = 'UPDATEDEFAULTVALUEERROR_FOR_FORMSIGN'; // 編輯表單資料錯誤訊息
export const SHOW_FORMLOADMESSAGE                 = 'SHOW_FORMLOADMESSAGE'; 				// 顯示提示訊息 