export const REFRESHING_CLEARN = 'REFRESHING_CLEARN';   //清資料的重整 
export const REFRESHING        = 'REFRESHING';   //更新中
export const REFRESH_ERROR     = 'REFRESH_ERROR';  //更新出錯
export const REFRESH_SUCCESS   = 'REFRESH_SUCCESS';  //更新成功

export const LOADFUNCTION    = 'LOADFUNCTION';
export const LOADNOTICE      = 'LOADNOTICE';
export const LOCKNOTICELISTSTATE = 'LOCKNOTICELISTSTATE';
export const CLEANNOTICELISTSTATE = 'CLEANNOTICELISTSTATE';
export const LOADFUNCTIONTYPE    = 'LOADFUNCTIONTYPE';
export const SET_HONE_FUNCTION_NUMBER    = 'SET_HONE_FUNCTION_NUMBER'; //設定首頁常見功能要顯示幾個
