export const MESSAGE_REFRESHING      = 'MESSAGE_REFRESHING';   		//更新中→此部分更新指畫面更新
export const MESSAGE_REFRESH_ERROR   = 'MESSAGE_REFRESH_ERROR';  	//更新出錯
export const MESSAGE_REFRESH_SUCCESS = 'MESSAGE_REFRESH_SUCCESS';  	//更新成功
export const STATE_UPDATE            = 'STATE_UPDATE'; 				//消息更新→此部分更新指消息已讀未讀更新
export const SHOWFOOTER              = 'SHOWFOOTER'; 				//顯示底部載入畫面
export const LOADINITIAL             = 'LOADINITIAL'; 				//初次載入
export const LOADMORE                = 'LOADMORE'; 					//載入更多
export const REMOVE_UNREAD			 = 'REMOVE_UNREAD';
export const REMOVE_ALLUNREAD		 = 'REMOVE_ALLUNREAD'
