export const SALARY_REFRESHING      = 'SALARY_REFRESHING';
export const GET_SALARY_SELECT_DAYS = 'GET_SALARY_SELECT_DAYS'; 
export const GETMISSALAY_SUCCESS    = 'GETMISSALAY_SUCCESS';  
export const GETMISSALAY_FAIL       = 'GETMISSALAY_FAIL';  
