export const CREATESURVEY_REFRESHING = 'CREATESURVEY_REFRESHING';
export const RENDERSURVEYFORMAT      = 'RENDERSURVEYFORMAT'; 
export const RENDERSURVEYFORMATERROR = 'RENDERSURVEYFORMATERROR'; 
export const UPDATEDEFAULTVALUE      = 'UPDATEDEFAULTVALUE';
export const UPDATEDEFAULTVALUEERROR = 'UPDATEDEFAULTVALUEERROR';
export const CLOSESURVEYFORM         = 'CLOSESURVEYFORM';
export const CHECKREQUIREDVALUE      = 'CHECKREQUIREDVALUE';
export const REGISTERSURVEYRESULT    = 'REGISTERSURVEYRESULT';
export const SURVEY_REFRESHING       = 'SURVEY_REFRESHING';
export const SURVEY_REFRESHING_END   = 'SURVEY_REFRESHING_END';
// export const DEFAULTSUBMITRESULT  = 'DEFAULTSUBMITRESULT';

